insert into track (trackid, trackname, trackartist) values (4, 'Treeflex', 27);
insert into track (trackid, trackname, trackartist) values (8, 'Wrapsafe', 18);
insert into track (trackid, trackname, trackartist) values (16, 'Stim', 26);
insert into track (trackid, trackname, trackartist) values (7, 'Bitwolf', 32);
insert into track (trackid, trackname, trackartist) values (13, 'Namfix', 39);
insert into track (trackid, trackname, trackartist) values (6, 'Matsoft', 24);
insert into track (trackid, trackname, trackartist) values (10, 'Biodex', 28);
insert into track (trackid, trackname, trackartist) values (8, 'Quo Lux', 36);
insert into track (trackid, trackname, trackartist) values (16, 'Aerified', 21);
insert into track (trackid, trackname, trackartist) values (12, 'Temp', 38);
insert into track (trackid, trackname, trackartist) values (6, 'Gembucket', 39);
insert into track (trackid, trackname, trackartist) values (10, 'Cookley', 5);
insert into track (trackid, trackname, trackartist) values (2, 'Ventosanzap', 32);
insert into track (trackid, trackname, trackartist) values (9, 'Alpha', 31);
insert into track (trackid, trackname, trackartist) values (7, 'Redhold', 9);
insert into track (trackid, trackname, trackartist) values (4, 'Biodex', 16);
insert into track (trackid, trackname, trackartist) values (16, 'Bigtax', 21);
insert into track (trackid, trackname, trackartist) values (12, 'Redhold', 14);
insert into track (trackid, trackname, trackartist) values (1, 'Fix San', 17);
insert into track (trackid, trackname, trackartist) values (15, 'Tampflex', 3);
insert into track (trackid, trackname, trackartist) values (3, 'Home Ing', 2);
insert into track (trackid, trackname, trackartist) values (1, 'Zoolab', 31);
insert into track (trackid, trackname, trackartist) values (15, 'Aerified', 39);
insert into track (trackid, trackname, trackartist) values (4, 'Cookley', 33);
insert into track (trackid, trackname, trackartist) values (16, 'Mat Lam Tam', 27);
insert into track (trackid, trackname, trackartist) values (9, 'Tres-Zap', 36);
insert into track (trackid, trackname, trackartist) values (14, 'Andalax', 25);
insert into track (trackid, trackname, trackartist) values (1, 'Tin', 15);
insert into track (trackid, trackname, trackartist) values (15, 'Andalax', 15);
insert into track (trackid, trackname, trackartist) values (15, 'Rank', 29);
insert into track (trackid, trackname, trackartist) values (14, 'Stronghold', 3);
insert into track (trackid, trackname, trackartist) values (17, 'Temp', 26);
insert into track (trackid, trackname, trackartist) values (14, 'Zoolab', 31);
insert into track (trackid, trackname, trackartist) values (7, 'Y-find', 19);
insert into track (trackid, trackname, trackartist) values (17, 'Cookley', 32);
insert into track (trackid, trackname, trackartist) values (11, 'Konklab', 30);
insert into track (trackid, trackname, trackartist) values (12, 'Fintone', 3);
insert into track (trackid, trackname, trackartist) values (8, 'Solarbreeze', 37);
insert into track (trackid, trackname, trackartist) values (7, 'Keylex', 25);
insert into track (trackid, trackname, trackartist) values (13, 'Quo Lux', 23);
insert into track (trackid, trackname, trackartist) values (1, 'Temp', 28);
insert into track (trackid, trackname, trackartist) values (2, 'Keylex', 13);
insert into track (trackid, trackname, trackartist) values (2, 'Zoolab', 13);
insert into track (trackid, trackname, trackartist) values (4, 'Zathin', 10);
insert into track (trackid, trackname, trackartist) values (9, 'Home Ing', 2);
insert into track (trackid, trackname, trackartist) values (10, 'Vagram', 11);
insert into track (trackid, trackname, trackartist) values (8, 'Tres-Zap', 29);
insert into track (trackid, trackname, trackartist) values (4, 'Konklab', 4);
insert into track (trackid, trackname, trackartist) values (13, 'Hatity', 18);
insert into track (trackid, trackname, trackartist) values (9, 'Matsoft', 39);
insert into track (trackid, trackname, trackartist) values (3, 'Stringtough', 34);
insert into track (trackid, trackname, trackartist) values (6, 'Matsoft', 23);
insert into track (trackid, trackname, trackartist) values (10, 'Redhold', 12);
insert into track (trackid, trackname, trackartist) values (14, 'Regrant', 36);
